apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api
  namespace: cert-manager
  annotations:
      argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: cloudflare-api
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        email: "{{ .email }}"
        token: "{{ .token }}"
  data:
    - secretKey: email
      remoteRef:
        key: cloudflare-api
        property: "username"
    - secretKey: token
      remoteRef:
        key: cloudflare-api
        property: "password"