apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
  annotations:
      argocd.argoproj.io/sync-wave: "1" # Do after secret
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jason@avon-lea.co.uk
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: jason@avon-lea.co.uk
            apiTokenSecretRef:
              name: cloudflare-api
              key: token
