{
 "title": "External Secrets",
 "tags": [
  "secrets",
  "external-secrets"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sync calls — Error/Total",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (exported_namespace, name) (present_over_time(externalsecret_sync_calls_total[$__interval]))",
     "legendFormat": "total: {{ exported_namespace }}: {{ name }}"
    },
    {
     "expr": "rate(externalsecret_sync_calls_error[$__interval])",
     "legendFormat": "error: {{ exported_namespace }}: {{ name }}"
    }
   ]
  },
  {
   "title": "Reconcile Duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (exported_namespace, name) (externalsecret_reconcile_duration)",
     "legendFormat": "{{ exported_namespace }}: {{ name }}"
    }
   ]
  },
  {
   "title": "Status Condition",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(name) (externalsecret_status_condition)",
     "legendFormat": "{{ backend }}: {{ name }}"
    }
   ]
  }
 ]
}