apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-secret-store-app
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    repoURL: https://github.com/xorima/byte-haven.git
    targetRevision: HEAD
    path: k8s/envs/sg/core-infra/external-secrets-secret-stores
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
