apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    repoURL: https://github.com/xorima/byte-haven.git
    targetRevision: HEAD
    path: k8s/envs/sg/core-infra/metrics-server

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
