---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onepassword-connect-credentials
  namespace: onepassword
  annotations:
    argocd.argoproj.io/sync-wave: "15" # Do after all else
    argocd.argoproj.io/sync-options: Validate=false
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: onepassword-connect-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        1password-credentials.json: "{{ .creds | b64enc }}"
  data:
    - secretKey: creds
      remoteRef:
        key: 1password-credentials
        property: 1password-credentials.json
        decodingStrategy: None
