---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onepassword-connect-token
  annotations:
    argocd.argoproj.io/sync-wave: "12" # Do after all else
    argocd.argoproj.io/sync-options: Validate=false
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: onepassword-connect-token
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: 1password-access-token
        property: credential
