apiVersion: v1
kind: Namespace
metadata:
  name: utilities
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Do first
    argocd.argoproj.io/sync-options: Validate=false ServerSideApply=true
spec:
  finalizers:
    - kubernetes
