all:
  vars:
    ansible_user: ansible
    ansible_ssh_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ssh_key_url: https://github.com/xorima.keys
    k3s_version: v1.30.2+k3s2
    token: "SET_AT_RUNTIME"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    cluster_context: sg-k3s
    my_user: "SET_AT_RUNTIME"
    my_password: "SET_AT_RUNTIME"
  children: 
    k3s_cluster:
      children:
        master:
          hosts: 
            sg-ctrl1:
              ansible_host: 192.168.30.61
        node:
          hosts:
            sg-worker1:
              ansible_host: 192.168.30.71
            sg-worker2:
              ansible_host: 192.168.30.72
localhost:
  vars:
    ansible_python_interpreter: /usr/bin/env python3