apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Validate=false ServerSideApply=true
spec:
  finalizers:
    - kubernetes
