apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuer-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Do after helm
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    repoURL: https://github.com/xorima/byte-haven.git
    targetRevision: HEAD
    path: k8s/envs/sg/core-infra/cert-manager-issuer

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
