apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Do after namespace
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.12.1
    helm:
      version: v3
      releaseName: metrics-server
      parameters:
        - name: "replicas"
          value: "2"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics-server
